title: Wenhao Yang
subtitle: Ph.D. Candidate
description: >- # this means to ignore newlines until "baseurl:"
  Wenhao Yand's personal website

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    - text: Shop
      url : /shop
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: yang.png
author: Wenhao Yang
author_bio: Engineering Ph.D. Candidate with experience in human-robot interaction, robotics manipulation, AR/VR. Strong background in Robotics and Simulation. Seeking a Research/Engineering position in the field of robotics or AR/VR.
research_interests: Human-robot Interaction, Robotics manipulation, Programming by Demonstration, Robotics System Design, Augmented & Virtual Reality, Human Factors, Tele-robots, Cobots, AGVs, Mobile Manipulators, Cyber-Physical Systems, Digital Twin, Industry 4.0, Smart Factory
author_email: "wy7711@rit.edu"
author_location: United States
author_website_url: "https://vinkoyang.github.io/"
typewrite-text: Dream big. Start small. But most of all start.
hero_cover_img: cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Education
author_education_details:
              - college_logo: rit.png
                college_name: Rochester Institute of Technology
                college_year: 2019 - 2023
                college_url: https://www.rit.edu/
                college_degree: PhD
                description: Engineering Ph.D. Program 
                visibility: true

              - college_logo: HKUST.png
                college_name: The Hong Kong University of Science and Technology
                college_year: 2018 - 2019
                college_url: https://hkust.edu.hk/
                college_degree: MSc
                description: Major - Mechanical Engineering | GPA 4.0/4.0
                visibility: true

              - college_logo: NUAA.png
                college_name: Nanjing University of Aeronautics and Astronautics
                college_year: 2014 - 2018
                college_url: https://nuaa.edu.cn/
                college_degree: BS
                description: Major - Aircraft Design and Engineering | GPA 3.9/5.0 Rank 35/302
                visibility: true

# Experiences
author_work_experiences:
            - company_name: Rochester Institute of Technology
              company_year: Aug. 2019 – Aug. 2023
              company_logo: rit.png
              company_url: https://www.rit.edu/
              designation: Research Assistant 
              description: Responsible for supporting and assisting Dr. Yunbo Zhang in various research activities and projects in robotic manipulation, human-robot interaction, and AR/VR.
              visibility: true

            - company_name: OPPO US Research Center (Innopeak Tech)
              company_year: Jun. 2022 – Sep. 2022
              company_logo: Oppo-logo.png
              company_url: https://www.innopeaktech.com/
              designation: Research Interns 
              description: A Mixed Reality robot remote control system was developed and implemented on Microsoft HoloLens 2, which allows for remote interaction with an Automated Guided Vehicle (Rover Pro).
              visibility: true

            - company_name: Rochester Institute of Technology
              company_year: Aug. 2021 – May.2022
              company_logo: rit.png
              company_url: https://www.rit.edu/
              designation: Teaching Assistant 
              description: Taking the lab session of 3D Printing (ISEE-741) and Materials Processing (ISEE-140)
              visibility: true

            - company_name: Guangdong Bright Dream Robotics Co., Ltd. (BDR)
              company_year: May. 2019 – Aug. 2019
              company_logo: BDR.png
              company_url: https://www.bzlrobot.com/
              designation: Internship 
              description: Design and develop the control system of the 6-DOF robot for a paving tiles machine.
              visibility: true

# Publication
author_publication_details:
            - publication_title: “I can see your password”&#58; A case study about cybersecurity risks in mid-air interactions of Mixed reality-based smart manufacturing applications
              publication_thumbnail: 2023_JCISE.jpg
              publication_authors: <b>Wenhao Yang</b>, Xiwen Dengxiong, Xueting Wang, Yidan Hu, & Yunbo Zhang
              publication_year: 2023
              publication_booktitle: Journal of Computing and Information Science in Engineering
              publication_description:
              publication_url: https://asmedigitalcollection.asme.org/computingengineering/article-abstract/doi/10.1115/1.4062658/1163679/I-can-see-your-password-A-case-study-about?redirectedFrom=fulltext
              #Citation Format: APA
              publication_citation: Yang, W., Dengxiong, X., Wang, X., Hu, Y., & Zhang, Y. (2023). “I can see your password”&#58; A case study about cybersecurity risks in mid-air interactions of mixed reality-based smart manufacturing applications. Journal of Computing and Information Science in Engineering, 1-12.
              visibility: true

            - publication_title: HAR<sup>2</sup>bot&#58; System Design of a Human-centered Augmented Reality Robot Programming Interface with Cognition Awareness
              publication_thumbnail: 2023_JIM.jpg
              publication_authors: <b>Wenhao Yang</b>, Qinqin Xiao, & Yunbo Zhang
              publication_year: 2023
              publication_booktitle: Journal of Intelligent Manufacturing
              publication_description:
              publication_url: https://link.springer.com/article/10.1007/s10845-023-02096-2
              #Citation Format: APA
              publication_citation: Yang, W., Xiao, Q., & Zhang, Y. (2023). HA R 2 bot&#58; a human-centered augmented reality robot programming method with the awareness of cognitive load. Journal of Intelligent Manufacturing, 1-19.
              visibility: true

            - publication_title: Visualization Error Analysis for Augmented Reality Stereo Video SeeThrough Head-Mounted Displays in Industry 4.0 Applications
              publication_thumbnail: 2022_MSEC.jpg
              publication_authors: <b>Wenhao Yang</b>, Yunbo Zhang
              publication_year: 2022
              publication_booktitle: International Manufacturing Science and Engineering Conference
              publication_description:
              publication_url: https://asmedigitalcollection.asme.org/MSEC/proceedings-abstract/MSEC2022/V002T06A016/1147062
              #Citation Format: APA
              publication_citation: Yang, W., & Zhang, Y. (2022, June). Visualization Error Analysis for Augmented Reality Stereo Video See-Through Head-Mounted Displays in Industry 4.0 Applications. In International Manufacturing Science and Engineering Conference (Vol. 85819, p. V002T06A016). American Society of Mechanical Engineers.
              visibility: true

            - publication_title: An Augmented-Reality Based Human-Robot Interface for Robotics Programming in the Complex Environment
              publication_thumbnail: 2021_MSEC.jpg
              publication_authors: <b>Wenhao Yang</b>, Qinqin Xiao, & Yunbo Zhang
              publication_year: 2021
              publication_booktitle: International Manufacturing Science and Engineering Conference
              publication_description:
              publication_url: https://asmedigitalcollection.asme.org/MSEC/proceedings-abstract/MSEC2021/85079/1115433
              #Citation Format: APA
              publication_citation: Yang, W., Xiao, Q., & Zhang, Y. (2021, June). An Augmented-Reality Based Human-Robot Interface for Robotics Programming in the Complex Environment. In International Manufacturing Science and Engineering Conference (Vol. 85079, p. V002T07A003). American Society of Mechanical Engineers.
              visibility: true

# Projects
author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true

# social links
twitter_username: johndoe
github_username:  sujaykundu777
facebook_username: johndoe
linkedin_username: johndoe
behance_username: johndoe
instagram_username: johndoe
medium_username: johndoe
telegram_username: johndoe
dribbble_username: johndoe
flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
show_author_publication_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
